package com.figueroa.valentines.ui.theme

import androidx.compose.ui.graphics.Color

val valentinesThemeLightPrimary = Color(0xFFB4262B)
val valentinesThemeLightOnPrimary = Color(0xFFFFFFFF)
val valentinesThemeLightPrimaryContainer = Color(0xFFFFDAD7)
val valentinesThemeLightOnPrimaryContainer = Color(0xFF410004)
val valentinesThemeLightSecondary = Color(0xFFB21E63)
val valentinesThemeLightOnSecondary = Color(0xFFFFFFFF)
val valentinesThemeLightSecondaryContainer = Color(0xFFFFD9E2)
val valentinesThemeLightOnSecondaryContainer = Color(0xFF3E001D)
val valentinesThemeLightTertiary = Color(0xFF9C413E)
val valentinesThemeLightOnTertiary = Color(0xFFFFFFFF)
val valentinesThemeLightTertiaryContainer = Color(0xFFFFDAD7)
val valentinesThemeLightOnTertiaryContainer = Color(0xFF410004)
val valentinesThemeLightError = Color(0xFFBA1A1A)
val valentinesThemeLightErrorContainer = Color(0xFFFFDAD6)
val valentinesThemeLightOnError = Color(0xFFFFFFFF)
val valentinesThemeLightOnErrorContainer = Color(0xFF410002)
val valentinesThemeLightBackground = Color(0xFFFFFBFF)
val valentinesThemeLightOnBackground = Color(0xFF201A1A)
val valentinesThemeLightSurface = Color(0xFFFFFBFF)
val valentinesThemeLightOnSurface = Color(0xFF201A1A)
val valentinesThemeLightSurfaceVariant = Color(0xFFF5DDDB)
val valentinesThemeLightOnSurfaceVariant = Color(0xFF534342)
val valentinesThemeLightOutline = Color(0xFF857371)
val valentinesThemeLightInverseOnSurface = Color(0xFFFBEEEC)
val valentinesThemeLightInverseSurface = Color(0xFF362F2E)
val valentinesThemeLightInversePrimary = Color(0xFFFFB3AE)
val valentinesThemeLightShadow = Color(0xFF000000)
val valentinesThemeLightSurfaceTint = Color(0xFFB4262B)
val valentinesThemeLightOutlineVariant = Color(0xFFD8C2C0)
val valentinesThemeLightScrim = Color(0xFF000000)

val valentinesThemeDarkPrimary = Color(0xFFFFB3AE)
val valentinesThemeDarkOnPrimary = Color(0xFF68000C)
val valentinesThemeDarkPrimaryContainer = Color(0xFF910617)
val valentinesThemeDarkOnPrimaryContainer = Color(0xFFFFDAD7)
val valentinesThemeDarkSecondary = Color(0xFFFFB1C8)
val valentinesThemeDarkOnSecondary = Color(0xFF650033)
val valentinesThemeDarkSecondaryContainer = Color(0xFF8E004A)
val valentinesThemeDarkOnSecondaryContainer = Color(0xFFFFD9E2)
val valentinesThemeDarkTertiary = Color(0xFFFFB3AE)
val valentinesThemeDarkOnTertiary = Color(0xFF5F1415)
val valentinesThemeDarkTertiaryContainer = Color(0xFF7E2A29)
val valentinesThemeDarkOnTertiaryContainer = Color(0xFFFFDAD7)
val valentinesThemeDarkError = Color(0xFFFFB4AB)
val valentinesThemeDarkErrorContainer = Color(0xFF93000A)
val valentinesThemeDarkOnError = Color(0xFF690005)
val valentinesThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val valentinesThemeDarkBackground = Color(0xFF201A1A)
val valentinesThemeDarkOnBackground = Color(0xFFEDE0DE)
val valentinesThemeDarkSurface = Color(0xFF201A1A)
val valentinesThemeDarkOnSurface = Color(0xFFEDE0DE)
val valentinesThemeDarkSurfaceVariant = Color(0xFF534342)
val valentinesThemeDarkOnSurfaceVariant = Color(0xFFD8C2C0)
val valentinesThemeDarkOutline = Color(0xFFA08C8B)
val valentinesThemeDarkInverseOnSurface = Color(0xFF201A1A)
val valentinesThemeDarkInverseSurface = Color(0xFFEDE0DE)
val valentinesThemeDarkInversePrimary = Color(0xFFB4262B)
val valentinesThemeDarkShadow = Color(0xFF000000)
val valentinesThemeDarkSurfaceTint = Color(0xFFFFB3AE)
val valentinesThemeDarkOutlineVariant = Color(0xFF534342)
val valentinesThemeDarkScrim = Color(0xFF000000)

val seed = Color(0xFFDF4646)
